name: Build Cordova App

on:
  push:
    branches:
      - main  # Запускать на изменения в ветке main

jobs:
  build:
    runs-on: ubuntu-latest  # Будет запускаться на Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Получаем код из репозитория

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Указываем версию Node.js 16 или выше

      - name: Install dependencies
        run: |
          npm install -g cordova  # Устанавливаем Cordova глобально
          npm install  # Устанавливаем зависимости проекта

      - name: Add Android platform
        run: |
          cordova platform add android  # Добавляем платформу Android

      - name: Create directories for APK (if not exists)
        run: |
          if [ ! -d "platforms/android/app/build/outputs/apk/release" ]; then  # Проверяем, существует ли директория
            mkdir -p platforms/android/app/build/outputs/apk/release  # Если не существует, создаем её
            echo "Directory created: platforms/android/app/build/outputs/apk/release"
          else
            echo "Directory already exists: platforms/android/app/build/outputs/apk/release"
          fi

      - name: Build Android app
        run: |
          cordova prepare android  # Подготовка проекта для Android
          cordova build android --release  # Строим приложение для Android с флагом --release для релиза

      - name: List APK files
        run: |
          ls platforms/android/app/build/outputs/apk/release  # Проверим, что есть APK

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4  # Обновлено на версию v4
        with:
          name: cordova-app-apk
          path: platforms/android/app/build/outputs/apk/release/*.apk  # Загрузим все APK

      - name: Commit APK to GitHub repository
        run: |
          cd platforms/android/app/build/outputs/apk/release
          mv app-release-unsigned.apk ../../../../../../../  # Перемещаем файл на уровень выше
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add app-release-unsigned.apk  # Добавляем APK в индекс git
          git commit -m "Add APK file to repository"
          git push origin main  # Пушим APK в репозиторий
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Для авторизации на GitHub

